version: "3.9"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped